# Anchor
docker_config:
  - &docker_config
      docker:
        - image: circleci/android:api-28-alpha
      environment:
        JAVA_OPTS: -Xmx1536m
      working_directory: ~/repo

gradle_sudo_command:
  - &gradle_sudo_command
      name: Chmod permissions 
      command: sudo chmod +x ./gradlew

# Circle Jobs
version: 2
jobs:
  build:
    <<: *docker_config

    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum "app/build.gradle.kts" }}
      - run: *gradle_sudo_command
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum "app/build.gradle.kts" }}
          paths:
            - ~/.gradle
  check:
    <<: *docker_config

    steps:
      - checkout
      - restore_cache:
          key: bundle-{{ checksum "Gemfile.lock" }}
      - run:
          name: Bundle install
          command: bundle install --path vendor/bundle
      - run: *gradle_sudo_command
      - run:
          name: Check
          command: |
              echo "CIRCLE_BRANCH : ${CIRCLE_BRANCH}"
              echo "App Build Type : ${APP_BUILD_TYPE}"
              if [ ! $CIRCLE_BRANCH = 'master' -a ! $CIRCLE_BRANCH = 'release' ]; then
                  ./gradlew --stacktrace lint${APP_BUILD_TYPE^}
                  ./gradlew --stacktrace ktlint${APP_BUILD_TYPE^}Check
                  bundle exec danger
              fi
      - save_cache:
          paths:
            - vendor/bundle
          key: bundle-{{ checksum "Gemfile.lock" }}
      - store_artifacts:
          path: app/build/reports
          destination: reports

# Workflows
workflows:
  version: 2
  build-check:
    jobs:
      - build
      - check:
          requires:
            - build